print(" This is basic Science quiz. There are some question related to Chemistry and Equations")
input("What is the Symbol of Sodium in Periodic Table? ")
input("What is the Symbol of Potassium in Periodic Table?")
input("How many electrons does Oxygen have?")
input("What is the Symbol of Argon in Periodic Table?")
input("What is the Symbol of Calcium in Periodic Table?")
input("How many electrons does Carbon have? ")
input("What is the Symbol of Carbon in Periodic Table?")
input("What is the Symbol of Neon in Periodic Table?")
input("How many electerons does Argon have? ")